title: Ipsum Community
description: One place, all texts, powered by everyone
url: https://ipsum-community.github.io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed

collections:
  ipsum:
    output: true
    permalink: /:path/
